apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    kubeflow-resource-stopped: '2024-04-05T01:02:39Z'
    notebooks.opendatahub.io/inject-oauth: 'true'
    opendatahub.io/image-display-name: CUDA
    notebooks.opendatahub.io/oauth-logout-url: 'https://rhods-dashboard-redhat-ods-applications.apps.cchase-summit.4ki0.p1.openshiftapps.com/projects/image-generation?notebookLogout=image-generation'
    opendatahub.io/accelerator-name: migrated-gpu
    openshift.io/description: ''
    openshift.io/display-name: Image Generation
    notebooks.opendatahub.io/last-image-selection: 'minimal-gpu:2023.2'
    notebooks.opendatahub.io/last-size-selection: Medium
    opendatahub.io/username: cchase@redhat.com
  name: image-generation
  namespace: image-generation
  labels:
    app: image-generation
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
spec:
  template:
    spec:
      affinity: {}
      containers:
        - resources:
            limits:
              cpu: '6'
              memory: 24Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '3'
              memory: 24Gi
              nvidia.com/gpu: '1'
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/image-generation/image-generation/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: image-generation
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/image-generation/image-generation/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/image-generation/image-generation
                                  --ServerApp.quit_button=False
                                  --ServerApp.tornado_settings={"user":"cchase-40redhat-2ecom","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.cchase-summit.4ki0.p1.openshiftapps.com","hub_prefix":"/projects/image-generation"}
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2023.2'
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: image-generation
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/certs/custom-ca-bundle.crt
              name: trusted-ca
              readOnly: true
              subPath: custom-ca-bundle.crt
          envFrom:
            - secretRef:
                name: aws-connection-my-storage
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/minimal-gpu:2023.2'
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: oauth-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: oauth-proxy
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8443
              name: oauth-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          image: 'registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46'
          args:
            - '--provider=openshift'
            - '--https-address=:8443'
            - '--http-address='
            - '--openshift-service-account=image-generation'
            - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
            - '--cookie-expire=24h0m0s'
            - '--tls-cert=/etc/tls/private/tls.crt'
            - '--tls-key=/etc/tls/private/tls.key'
            - '--upstream=http://localhost:8888'
            - '--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            - '--email-domain=*'
            - '--skip-provider-button'
            - '--openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"image-generation","namespace":"$(NAMESPACE)"}'
            - '--logout-url=https://rhods-dashboard-redhat-ods-applications.apps.cchase-summit.4ki0.p1.openshiftapps.com/projects/image-generation?notebookLogout=image-generation'
      enableServiceLinks: false
      serviceAccountName: image-generation
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - name: image-generation
          persistentVolumeClaim:
            claimName: image-generation
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            items:
              - key: ca-bundle.crt
                path: custom-ca-bundle.crt
              - key: odh-ca-bundle.crt
                path: custom-odh-ca-bundle.crt
            name: odh-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: image-generation-oauth-config
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: image-generation-tls
