"""Utility package exports."""

from .ids import (
    IDGenerator,
    extract_prefix_from_id,
    extract_uuid_from_id,
    generate_batch_id,
    generate_correlation_id,
    generate_id,
    generate_image_id,
    generate_request_id,
    generate_session_id,
    generate_short_id,
    generate_timestamped_id,
    generate_uuid,
    image_id_generator,
    is_valid_prefixed_id,
    is_valid_uuid,
    request_id_generator,
    session_id_generator,
)
from .images import (
    FORMAT_EXTENSIONS,
    FORMAT_MIME_TYPES,
    SUPPORTED_EXTENSIONS,
    SUPPORTED_FORMATS,
    SUPPORTED_MIME_TYPES,
    ImageFormatError,
    ImageSizeError,
    ImageValidationError,
    create_image_filename,
    decode_image_base64,
    detect_image_format,
    encode_image_base64,
    format_file_size,
    get_file_extension,
    get_image_dimensions,
    get_mime_type,
    validate_image,
    validate_image_dimensions,
    validate_image_format,
    validate_image_size,
)
from .logging import (
    RequestLoggingMiddleware,
    bind_context,
    clear_context,
    configure_logging,
    get_logger,
    log_function_call,
    with_request_id,
)

__all__ = [
    # ID generation
    "generate_uuid",
    "generate_id",
    "generate_image_id",
    "generate_request_id",
    "generate_session_id",
    "generate_timestamped_id",
    "generate_short_id",
    "generate_correlation_id",
    "generate_batch_id",
    "is_valid_uuid",
    "is_valid_prefixed_id",
    "extract_uuid_from_id",
    "extract_prefix_from_id",
    "IDGenerator",
    "image_id_generator",
    "request_id_generator",
    "session_id_generator",
    # Image utilities
    "detect_image_format",
    "validate_image_format",
    "validate_image_size",
    "validate_image_dimensions",
    "validate_image",
    "get_image_dimensions",
    "encode_image_base64",
    "decode_image_base64",
    "get_mime_type",
    "get_file_extension",
    "create_image_filename",
    "format_file_size",
    "SUPPORTED_FORMATS",
    "SUPPORTED_EXTENSIONS",
    "SUPPORTED_MIME_TYPES",
    "FORMAT_EXTENSIONS",
    "FORMAT_MIME_TYPES",
    "ImageValidationError",
    "ImageFormatError",
    "ImageSizeError",
    # Logging utilities
    "configure_logging",
    "get_logger",
    "bind_context",
    "clear_context",
    "with_request_id",
    "log_function_call",
    "RequestLoggingMiddleware",
]