apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mcp-server-base

# Common labels applied to all resources
labels:
  - pairs:
      app: mcp-server
      project: text-to-image-demo

# Common annotations applied to all resources
commonAnnotations:
  app.kubernetes.io/name: mcp-server
  app.kubernetes.io/part-of: text-to-image-demo
  app.kubernetes.io/version: v1.0
  app.kubernetes.io/managed-by: kustomize

# Resources to include in base
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

# ConfigMap generation for environment variables
configMapGenerator:
  - name: mcp-server-config
    literals:
      - DIFFUSERS_RUNTIME_URL=http://tiny-sd.default.svc.cluster.local:8080
      - DIFFUSERS_MODEL_ID=model
      - IMAGE_OUTPUT_PATH=/opt/app-root/src/images
      - PORT=8080
      - DIFFUSERS_RUNTIME_NAMESPACE=default

# Add version suffix to generated ConfigMaps
generatorOptions:
  disableNameSuffixHash: false

# Image configuration
images:
  - name: mcp-server
    newName: quay.io/cfchase/mcp-server
    newTag: latest

# Namespace (can be overridden in overlays)
namespace: mcp-server

