kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: diffusers-runtime-predictor
  namespace: single-model-serving
spec:
  to:
    kind: Service
    name: diffusers-runtime-predictor
    weight: 100
  port:
    targetPort: diffusers-runtime-predictor
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
