apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-server-images
  labels:
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi