apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secrets
  labels:
    component: configuration
type: Opaque
stringData:
  PLACEHOLDER: "placeholder-value"
  # Add any sensitive configuration here
  # Example: API_KEY: "your-api-key"