---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: ''
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: Llama-4
    opendatahub.io/template-name: llama-4
    openshift.io/display-name: llama-4
  name: llama-4
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: 'quay.io/modh/vllm:rhoai-2.22-cuda'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: Llama-4
    serving.kserve.io/deploymentMode: RawDeployment
  name: llama-4
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--model=/mnt/models'
        - '--served-model-name=llama-4-scout-17b-16e-w4a16'
        - '--tensor-parallel-size=4'
        - '--max-model-len=400000'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser'
        - llama4_pythonic
        - '--chat-template'
        - /app/data/template/tool_chat_template_llama4_pythonic.jinja
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '44'
          memory: 360Gi
          nvidia.com/gpu: '4'
        requests:
          cpu: '32'
          memory: 300Gi
          nvidia.com/gpu: '4'
      runtime: llama-4
      storageUri: oci://registry.redhat.io/rhelai1/modelcar-llama-4-scout-17b-16e-instruct-quantized-w4a16:1.5
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
